model:
  backbone_name: "resnet2d"
  backbone_family: "resnet2d"
  model_size: "base"
  img_size: [100, 200]
  embed_dim: 768
  drop_rate: 0.0
  drop_path_rate: 0.0
  downstream: false
  global_pool: "avg"
  stem_kernel: 7
  stem_stride: 2
  use_maxpool: true
